### ISSUE TITLE
Добавление коннекторов для CSV и MySQL

### ISSUE THREAD

**Issue by zxan2** [datalens-tech/datalens-backend#122]
Добрый день, хотел протестировать разные типы коннекторов, но при запуске через [docker-compose](https://github.com/datalens-tech/datalens#running-containers)  показывает всего 3 типа подключения: postgres, clickhouse и CHYT

хотя какие-то связанные файлы от новых коннекторов есть в коде https://github.com/datalens-tech/datalens-backend/tree/main/lib/dl_connector_mysql

также пытался добавлять тип коннектора mysql в файлы https://github.com/datalens-tech/datalens/blob/main/docker-compose.yml#L17 и https://github.com/datalens-tech/datalens/blob/main/backend-configs/api.yaml#L10 , получил следующую ошибку
![image](https://github.com/datalens-tech/datalens-backend/assets/80911150/1c142a2b-f9c3-4976-a930-14c457fc5bb5)

Эти коннекторы возможно как-то подключить и протестировать?

**Comment by KonstantAnxiety** [comment]
Hi! Everything necessary to enable existing connectors is present in our repositories, but they indeed lack the instruction on how to do this.

We will eventually enable all connectors and create relevant guides.

Closing this issue as a duplicate, for now you can follow these issues:
- File connector https://github.com/datalens-tech/datalens/issues/61
- MySQL https://github.com/datalens-tech/datalens/issues/34
