### ISSUE TITLE
ERROR [internal] load metadata for docker.io/library/bake_ctx_metapkg:latest

### ISSUE THREAD

**Issue by Alekovmsk** [datalens-tech/datalens-backend#448]
Aleksey@iMac-apple dl_control_api % docker build -t datalens-control_api:0.2080.0 .
[+] Building 2.9s (11/11) FINISHED                                                                                                           docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                         0.0s
 => => transferring dockerfile: 1.01kB                                                                                                                       0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4                                                                                                 1.8s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io                                                                                             0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc                            0.0s
 => [internal] load .dockerignore                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                              0.0s
 => ERROR [internal] load metadata for docker.io/library/bake_ctx_metapkg:latest                                                                             1.0s
 => CANCELED [internal] load metadata for docker.io/library/bake_ctx_base_img:latest                                                                         1.0s
 => CANCELED [internal] load metadata for docker.io/library/bake_ctx_src_lib:latest                                                                          1.0s
 => [auth] library/bake_ctx_metapkg:pull token for registry-1.docker.io                                                                                      0.0s
 => [auth] library/bake_ctx_src_lib:pull token for registry-1.docker.io                                                                                      0.0s
 => [auth] library/bake_ctx_base_img:pull token for registry-1.docker.io                                                                                     0.0s
------
 > [internal] load metadata for docker.io/library/bake_ctx_metapkg:latest:
------
Dockerfile:12
--------------------
  10 |     # Libs & metapkg
  11 |     COPY --from=bake_ctx_src_lib / /src
  12 | >>> COPY --from=bake_ctx_metapkg / /src
  13 |     
  14 |     # Sources copy
--------------------
ERROR: failed to solve: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by KonstantAnxiety** [comment]
Hey @Alekovmsk! Please check out the newly created "[How to build](https://github.com/datalens-tech/datalens-backend/blob/main/kb/how_to_build.md)" guide and let us know if there are any issues after that

**Comment by KonstantAnxiety** [comment]
Closing this issue as there is no reaction
